spring.application.name=treading-plateform

server.port=5454

spring.datasource.url=jdbc:h2:mem:treading;DB_CLOSE_DELAY=-1;NON_KEYWORDS=USER
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=akhileshkumar73822@gmail.com
spring.mail.password=amzf ygur objs npzy

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#stripe payment gatway
stripe.api.key=sk_test_placeholder
#
#razorpay payment gaytway
razorpay.api.key=rzp_test_M3UG7eHF9sMLDO

razorpay.api.secret=69ywmUTMCdK8bqiJuSD74EAv
#
#
# coingecko api key
coingecko.api.key=CG-5UEgD5uzxByz6d5LMGEv7Aaw
#
# gemini api key
gemini.api.key=placeholder_gemini_key
#
# google oauth2
spring.security.oauth2.client.registration.google.client-id=placeholder-client-id
spring.security.oauth2.client.registration.google.client-secret=placeholder-client-secret
spring.security.oauth2.client.registration.google.scope=profile,email

