export const GET_OPTION_CHAIN_REQUEST = 'GET_OPTION_CHAIN_REQUEST';
export const GET_OPTION_CHAIN_SUCCESS = 'GET_OPTION_CHAIN_SUCCESS';
export const GET_OPTION_CHAIN_FAILURE = 'GET_OPTION_CHAIN_FAILURE';

export const PLACE_OPTION_ORDER_REQUEST = 'PLACE_OPTION_ORDER_REQUEST';
export const PLACE_OPTION_ORDER_SUCCESS = 'PLACE_OPTION_ORDER_SUCCESS';
export const PLACE_OPTION_ORDER_FAILURE = 'PLACE_OPTION_ORDER_FAILURE';

export const GET_USER_OPTION_ORDERS_REQUEST = 'GET_USER_OPTION_ORDERS_REQUEST';
export const GET_USER_OPTION_ORDERS_SUCCESS = 'GET_USER_OPTION_ORDERS_SUCCESS';
export const GET_USER_OPTION_ORDERS_FAILURE = 'GET_USER_OPTION_ORDERS_FAILURE';
